on:
  push:
    branches: [main]
      
jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup node
      uses: actions/setup-node@v4
      with: 
          node-version: '22'
          cache: 'yarn'
          
    - name: Install
      run: yarn
        
  build:
      runs-on: ubuntu-latest
      needs: dependencies
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          
        - name: Setup node
          uses: actions/setup-node@v4
          with: 
            node-version: '22'
            cache: 'yarn'
            
        - name: Install
          run: yarn
          
        - name: Build
          run: yarn build
   

  linters:
      runs-on: ubuntu-latest
      needs: dependencies
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup node
          uses: actions/setup-node@v4
          with: 
            node-version: '22'
            cache: 'yarn'
        - name: Install
          run: yarn
        - name: Lint
          run: yarn lint 

  deploy:
    runs-on: ubuntu-latest
    needs: [dependencies,build]
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup node
          uses: actions/setup-node@v4
          with: 
            node-version: '22'
            cache: 'yarn'
        - name: Install
          run: yarn
        - name: Deploy
          run: yarn deploy 
        
  

